[tool.poetry]
name = "saize_env"
version = "0.1.0"
description = ""
authors = ["Natsuki0928 <longmonth28@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1, <=3.9"
pandas = "^1.2.4"
numpy = "^1.20.2"
streamlit = "^0.89.0"
mypulp = "^0.0.11"
importlib-resources = "^5.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"